import {Ingredient} from './types';

export const testIngredients: Ingredient[] = [
  {
    ingredientName: 'Banana',
    category: 'fruit',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: new Date('2023-05-01'),
    timestamp: Date.now() - 1000,
  },
  {
    ingredientName: 'Carrots',
    category: 'vegetable',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: new Date('2023-04-26'),
    timestamp: Date.now() - 2000,
  },
  {
    ingredientName: 'Milk',
    category: 'dairy',
    location: 'fridge',
    expirationDate: new Date('2023-04-25'),
    timestamp: Date.now() - 3000,
  },
  {
    ingredientName: 'Salmon',
    category: 'fish',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: new Date('2024-05-31'),
    timestamp: Date.now() - 2000,
  },
  {
    ingredientName: 'Chicken Thighs',
    category: 'meat',
    location: 'fridge',
    expirationDate: new Date('2023-04-27'),
    timestamp: Date.now() - 3000,
  },
  {
    ingredientName: 'Orange Juice',
    category: 'liquid',
    location: 'fridge',
    expirationDate: new Date('2023-04-30'),
    timestamp: Date.now() - 3000,
  },
  {
    ingredientName: 'Strawberries',
    category: 'fruit',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: new Date('2023-04-25'),
    timestamp: Date.now() - 4000,
  },
  {
    ingredientName: 'Green Beans',
    category: 'vegetable',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: new Date('2024-06-30'),
    timestamp: Date.now() - 5000,
  },
  {
    ingredientName: 'Cheddar Cheese',
    category: 'dairy',
    location: 'fridge',
    expirationDate: new Date('2023-05-05'),
    timestamp: Date.now() - 6000,
  },
  {
    ingredientName: 'Beef Roast',
    category: 'meat',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: new Date('2024-10-31'),
    timestamp: Date.now() - 7000,
  },
  {
    ingredientName: 'Canned Corn',
    category: 'vegetable',
    location: 'pantry',
    confectionType: 'canned',
    expirationDate: new Date('2024-12-31'),
    timestamp: Date.now() - 8000,
  },
  {
    ingredientName: 'Yogurt',
    category: 'dairy',
    location: 'fridge',
    confectionType: 'canned',
    expirationDate: new Date('2023-04-29'),
    timestamp: Date.now() - 9000,
  },
  {
    ingredientName: 'Tuna',
    category: 'fish',
    location: 'pantry',
    confectionType: 'canned',
    expirationDate: new Date('2024-07-31'),
    timestamp: Date.now() - 10000,
  },
  {
    ingredientName: 'Pork Chops',
    category: 'meat',
    location: 'fridge',
    expirationDate: new Date('2023-04-28'),
    timestamp: Date.now() - 11000,
  },
  {
    ingredientName: 'Lemon',
    category: 'fruit',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: new Date('2023-04-30'),
    timestamp: Date.now() - 12000,
  },
  {
    ingredientName: 'Spinach',
    category: 'vegetable',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: new Date('2023-04-26'),
    quantity: 7,
    timestamp: Date.now() - 13000,
  },
  {
    ingredientName: 'Frozen Peas',
    category: 'vegetable',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: new Date('2023-10-31'),
    quantity: 20,
    timestamp: Date.now() - 14000,
  },
  {
    ingredientName: 'Ground Beef',
    category: 'meat',
    location: 'fridge',
    expirationDate: new Date('2023-04-29'),
    quantity: 2,
    timestamp: Date.now() - 15000,
  },
];
