import {Ingredient} from './types';

export const testIngredients: Ingredient[] = [
  {
    ingredientName: 'Banana',
    category: 'fruit',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: new Date('2023-05-01'),
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    ingredientName: 'Carrots',
    category: 'vegetable',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: new Date('2023-04-26'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Milk',
    category: 'dairy',
    location: 'fridge',
    expirationDate: new Date('2023-04-25'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Salmon',
    category: 'fish',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: new Date('2024-05-31'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Chicken Thighs',
    category: 'meat',
    location: 'fridge',
    expirationDate: new Date('2023-04-27'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Orange Juice',
    category: 'liquid',
    location: 'fridge',
    expirationDate: new Date('2023-04-30'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Strawberries',
    category: 'fruit',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: new Date('2023-04-25'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Green Beans',
    category: 'vegetable',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: new Date('2024-06-30'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Cheddar Cheese',
    category: 'dairy',
    location: 'fridge',
    expirationDate: new Date('2023-05-05'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Beef Roast',
    category: 'meat',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: new Date('2024-10-31'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Canned Corn',
    category: 'vegetable',
    location: 'pantry',
    confectionType: 'canned',
    expirationDate: new Date('2024-12-31'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Yogurt',
    category: 'dairy',
    location: 'fridge',
    confectionType: 'canned',
    expirationDate: new Date('2023-04-29'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Tuna',
    category: 'fish',
    location: 'pantry',
    confectionType: 'canned',
    expirationDate: new Date('2024-07-31'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Pork Chops',
    category: 'meat',
    location: 'fridge',
    expirationDate: new Date('2023-04-28'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Lemon',
    category: 'fruit',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: new Date('2023-04-30'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Spinach',
    category: 'vegetable',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: new Date('2023-04-26'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Frozen Peas',
    category: 'vegetable',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: new Date('2023-10-31'),
    timestamp: Date.now(),
  },
  {
    ingredientName: 'Ground Beef',
    category: 'meat',
    location: 'fridge',
    expirationDate: new Date('2023-04-29'),
    timestamp: Date.now(),
  },
];
