import {Ingredient, Shop} from './types';

function daysFromNowOn(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);

  return date;
}

export const shops: Shop[] = [
  {
    name: 'MPreis Bozen',
    latitude: 46.498566,
    longitude: 11.3565227,
    type: ['fruit', 'vegetable', 'dairy', 'fish', 'meat', 'liquid'],
  },
  {
    name: 'Butcher Stampfl',
    latitude: 46.4999572,
    longitude: 11.3603236,
    type: ['meat'],
  },
  {
    name: 'Aldi Bozen',
    latitude: 46.5010481,
    longitude: 11.3414135,
    type: ['fruit', 'vegetable', 'dairy', 'fish', 'meat', 'liquid'],
  },
  {
    name: 'Butcher Grünberger',
    latitude: 46.502856,
    longitude: 11.3320079,
    type: ['meat'],
  },
];

export const testIngredients: Ingredient[] = [
  {
    ingredientName: 'Banana',
    category: 'fruit',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: daysFromNowOn(1),
    timestamp: Date.now() - 1000,
    ripeness: 'ripe',
    ripenessTimestamp: Date.now() - 1000,
    open: false,
  },
  {
    ingredientName: 'Carrots',
    category: 'vegetable',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: daysFromNowOn(2),
    timestamp: Date.now() - 2000,
    ripeness: 'green',
    ripenessTimestamp: Date.now() - 2000,
    open: false,
  },
  {
    ingredientName: 'Milk',
    category: 'dairy',
    location: 'fridge',
    expirationDate: daysFromNowOn(3),
    timestamp: Date.now() - 3000,
    open: false,
  },
  {
    ingredientName: 'Salmon',
    category: 'fish',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: daysFromNowOn(5),
    timestamp: Date.now() - 4000,
    open: false,
  },
  {
    ingredientName: 'Chicken Thighs',
    category: 'meat',
    location: 'fridge',
    expirationDate: daysFromNowOn(4),
    timestamp: Date.now() - 5000,
    open: false,
  },
  {
    ingredientName: 'Orange Juice',
    category: 'liquid',
    location: 'fridge',
    expirationDate: daysFromNowOn(1),
    timestamp: Date.now() - 6000,
    open: false,
  },
  {
    ingredientName: 'Strawberries',
    category: 'fruit',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: daysFromNowOn(3),
    timestamp: Date.now() - 7000,
    ripeness: 'green',
    ripenessTimestamp: Date.now() - 7000,
    open: false,
  },
  {
    ingredientName: 'Canned Corn',
    category: 'vegetable',
    location: 'pantry',
    confectionType: 'canned',
    expirationDate: daysFromNowOn(10),
    timestamp: Date.now() - 8000,
    open: false,
  },
  {
    ingredientName: 'Yogurt',
    category: 'dairy',
    location: 'fridge',
    confectionType: 'canned',
    expirationDate: daysFromNowOn(11),
    timestamp: Date.now() - 9000,
    open: false,
  },
  {
    ingredientName: 'Tuna',
    category: 'fish',
    location: 'pantry',
    confectionType: 'canned',
    expirationDate: daysFromNowOn(11),
    timestamp: Date.now() - 10000,
    open: false,
  },
  {
    ingredientName: 'Pork Chops',
    category: 'meat',
    location: 'fridge',
    expirationDate: daysFromNowOn(12),
    timestamp: Date.now() - 11000,
    open: false,
  },
  {
    ingredientName: 'Lemon',
    category: 'fruit',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: daysFromNowOn(13),
    timestamp: Date.now() - 12000,
    ripeness: 'advanced',
    ripenessTimestamp: Date.now() - 12000,
    open: false,
  },
  {
    ingredientName: 'Spinach',
    category: 'vegetable',
    location: 'fridge',
    confectionType: 'fresh',
    expirationDate: daysFromNowOn(14),
    quantity: 7,
    timestamp: Date.now() - 13000,
    ripeness: 'too ripe',
    ripenessTimestamp: Date.now() - 13000,
    open: false,
  },
  {
    ingredientName: 'Frozen Peas',
    category: 'vegetable',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: daysFromNowOn(15),
    quantity: 20,
    timestamp: Date.now() - 14000,
    open: false,
  },
  {
    ingredientName: 'Ground Beef',
    category: 'meat',
    location: 'fridge',
    expirationDate: daysFromNowOn(16),
    quantity: 2,
    timestamp: Date.now() - 15000,
    open: false,
  },
  {
    ingredientName: 'Green Beans',
    category: 'vegetable',
    location: 'freezer',
    confectionType: 'frozen',
    expirationDate: daysFromNowOn(17),
    timestamp: Date.now() - 16000,
    open: false,
  },
  {
    ingredientName: 'Cheddar Cheese',
    category: 'dairy',
    location: 'fridge',
    expirationDate: daysFromNowOn(3),
    timestamp: Date.now() - 17000,
    open: true,
  },
  {
    ingredientName: 'Beef Roast',
    category: 'meat',
    location: 'freezer',
    confectionType: 'fresh',
    expirationDate: daysFromNowOn(42),
    timestamp: Date.now() - 18000,
    ripeness: 'ripe',
    ripenessTimestamp: Date.now() - 18000,
    open: false,
  },
];
